### ISSUE TITLE
[기능] 프론트엔드에 이미지 생성 완료 알림

### ISSUE THREAD

**Issue by BambooKim** [GrimUriCapstone/backend#24]
# Firebase Cloud Messaging

[Firebase Cloud Messaging - Document](https://firebase.google.com/docs/cloud-messaging?hl=ko&authuser=0)

## 아키텍처 개요

![image](https://user-images.githubusercontent.com/42964867/232960503-5573cb08-caf3-4344-8fbd-8d68caa5e1a4.png)

1. **Message building and targeting**. 우리의 프로젝트에서는 백엔드 웹서버이다.
2. **FCM backend**. FCM 서비스이다.
3. **Platform-level message transport**. Android나 iOS의 경우 존재하는 레이어 또는 프로토콜인 것 같다.
4. **SDK on device**. 프론트엔드에서 처리해야 할 로직이다.

### 수명 주기 흐름
로직의 흐름, 구성해야 할 것들

* **FCM에서 메시지를 수신하도록 기기를 등록합니다.** 
* 다운스트림 메시지 전송 및 수신
  * 메시지를 보냅니다. 앱 서버가 클라이언트 앱에 메시지를 보냅니다.
    1. 메시지는 알림 작성기 또는 신뢰할 수 있는 환경에서 작성되며 메시지 요청이 FCM 백엔드로 전송됩니다.
    2. FCM 백엔드는 메시지 요청을 수신하고 메시지 ID와 기타 메타데이터를 생성하여 플랫폼별 전송 레이어로 보냅니다.
    3. 기기가 온라인 상태이면 메시지가 플랫폼별 전송 레이어를 통해 기기로 전송됩니다.
    4. 기기에서 클라이언트 앱이 메시지 또는 알림을 수신합니다.

# 메시지 정보

앱이 백그라운드에서 실행 중일 때 FCM SDK가 알림 표시를 자동으로 처리하게 하려면 알림 메시지를 사용하세요. 자체 클라이언트 앱 코드로 메시지를 처리하려면 데이터 메시지를 사용하세요.

FCM은 선택사항인 데이터 페이로드를 포함하는 알림 메시지를 보낼 수 있습니다. 이러한 경우 알림 페이로드 표시는 FCM에서 처리하고 데이터 페이로드는 클라이언트 앱에서 처리합니다.

## 알림 메시지

`notification`에 사전 정의된 키 옵션에 해당하는 값을 보낸다.
앱이 백그라운드인 경우, FCM SDK가 앱을 대신해 사용자 기기에 메시지를 표시한다.
앱이 포그라운드인 경우, 앱의 코드에 따라 동작이 결정된다.

### 예시
``` json
{
  "message":{
    "token":"bk3RNwTe3H0:CI2k_HHwgIpoDKCIZvvDMExUdFQ3P1...",
    "notification":{
      "title":"Portugal vs. Denmark",
      "body":"great match!"
    }
  }
}
```

사전 정의된 키
* `title`
* `body`

## 데이터 메시지

클라이언트 앱이 데이터 메시지 처리를 담당한다. 예약된 키 이름 없이 Custom 키-값 쌍만 있다.

> 커스텀 키-값 쌍에 예약어를 사용하지 않도록 합니다. 예약어에는 'from', 'notification', 'message_type', 또는 'google'이나 'gcm'으로 시작하는 모든 단어가 포함됩니다.

### 예시

``` json
{
  "message":{
    "token":"bk3RNwTe3H0:CI2k_HHwgIpoDKCIZvvDMExUdFQ3P1...",
    "data":{
      "Nick" : "Mario",
      "body" : "great match!",
      "Room" : "PortugalVSDenmark"
    }
  }
}
```

정보는 공통 `data` 키에 캡슐화되어 있다.

## Data Payload가 포함된 알림 메시지

커스텀 키-값 쌍의 선택적 페이로드를 포함하는 알림 메시지를 보낼 수 있습니다.

알림과 데이터 페이로드가 모두 포함된 메시지를 수신한 경우의 앱 동작은 앱이 백그라운드 상태인지 아니면 포그라운드 상태인지에 따라 다릅니다. 특히 수신 당시에 앱이 활성 상태였는지 여부에 따라 다릅니다.

* 백그라운드 상태인 경우 알림 페이로드가 앱의 알림 목록에 수신되며 사용자가 알림을 탭한 경우에만 앱에서 데이터 페이로드를 처리합니다.
* 포그라운드 상태인 경우 앱에서 페이로드가 둘 다 제공되는 메시지 객체를 수신합니다.

## 메시지 우선순위

다운스트림 메시지의 전송 우선순위(보통 및 높은 우선순위)를 할당할 수 있는 옵션 두 개가 있습니다. 이 동작은 플랫폼에 따라 조금씩 다르지만, 보통 및 높은 우선순위 메시지 전송이 작동하는 방식은 다음과 같습니다.

* **보통 우선순위**: 보통 우선순위 메시지는 앱이 포그라운드 상태이면 즉시 전송됩니다. 백그라운드 앱의 경우 전송이 지연될 수 있습니다. 새로운 이메일 알림, UI 동기화 유지, 백그라운드 앱 데이터 동기화와 같이 시간이 크게 중요하지 않은 메시지의 경우 보통 전송 우선순위를 선택하세요.

* **높은 우선순위**: FCM이 기기가 잠자기 모드인 경우에도 높은 우선순위 메시지를 즉시 전송하려고 시도합니다. 높은 우선순위 메시지는 사용자에게 표시되는 시간에 민감한 콘텐츠를 위한 것입니다.

## 사용자 인증 정보

<img width="767" alt="image" src="https://user-images.githubusercontent.com/42964867/232967948-a81a7c19-14c7-4e7b-8041-f947d828084e.png">

# FCM 등록 토큰 관리

## 등록 토큰 검색 및 저장

앱을 처음 시작할 때 FCM SDK가 클라이언트 앱 인스턴스용 등록 토큰을 생성한다. 이후 서버에 저장해야 한다.

## 잘못된 토큰 응답 감지

서버는... 비활성 토큰이나 잘못된 토큰임을 알게 된 경우 제거해야 한다.

## 등록 토큰 최신 상태 보장

서버는 정기적으로 등록된 토큰을 검색 및 업데이트하는 것이 좋다.

**Comment by BambooKim** [comment]
# 서버 환경 FCM 설정
[Firebase Cloud Messaging - Server](https://firebase.google.com/docs/cloud-messaging/server?hl=ko&authuser=0)

## 옵션

FCM HTTP v1 API를 사용하는 것을 권장하고 있다.

**Comment by BambooKim** [comment]
# 클라이언트 FCM 설정

## 웹(자바스크립트)
[Firebase Cloud Messaging - JavaScript](https://firebase.google.com/docs/cloud-messaging/js/client?hl=ko&authuser=0)

## Flutter
[Firebase Cloud Messaging - Flutter](https://firebase.google.com/docs/cloud-messaging/flutter/client?hl=ko&authuser=0)

@bluejoyq

**Comment by BambooKim** [comment]
## Front-Back 협조점

@bluejoyq 
* FCM 토큰 웹서버에 전달하는 시점
* 후보 이미지 목록 생성 이후, 클라이언트에 notification 전달 시 `data` 페이로드에 담길 정보

**Comment by bluejoyq** [comment]
확인했습니다. 수동으로 테스트해보고 연락드릴게요

**Comment by BambooKim** [comment]
## 새로 추가될 내용

* 로그인 후 FCM토큰 정보 전송 API: `POST`, spec 작성 예정
* AI 생성 서버로부터 완료 및 이미지 정보 수신 후 notification 생성 및 발신
   * 사용자의 기기들 (FCM 토큰들)에 전송
   * 알림 메시지 with 커스텀 data 페이로드 (title, body, data-diaryId, diaryTitle)

**Comment by BambooKim** [comment]
## FCM 토큰 정보 전송 API

### endpoint
* `/api/v1/user/fcmtoken`

### Method
* HTTP Post

### Header
* Authorization: Bearer { Token }

### Body
``` json
{
  "fcm_token": "string"
}
```
---
@bluejoyq

**Comment by BambooKim** [comment]
### Data Payload가 포함된 알림 메시지
``` json
 {
  "message":{
    "token":"bk3RNwTe3H0:CI2k_HHwgIpoDKCIZvvDMExUdFQ3P1...",
    "notification":{
      "title":"이미지 생성 완료!",
      "body":"일기 \"Example\"의 이미지 생성이 완료되었습니다."
    },
    "data": {
      "diaryId": "string",
      "diaryTitle": "string"
    }
  }
}
```

* 참고로 데이터 페이로드의 `diaryId`는 숫자가 아니라 문자열입니다. (FCM API 제약조건 상 문자열만 가능)
@bluejoyq
