### ISSUE TITLE
[기능] 처리율 제한 장치

### ISSUE THREAD

**Issue by bluejoyq** [GrimUriCapstone/backend#32]
- 단 내 계정은 예외루 ㅎㅎ
- 추가로 프로필 조회 시 최대 횟수, 남은 횟수도

**Comment by BambooKim** [comment]
MVP 이후로 개발하는 것으로 해도 괜찮겠죠?

**Comment by bluejoyq** [comment]
네 그러라고 enhancement 라벨 달았슴다

**Comment by BambooKim** [comment]
# 처리율 제한 장치
## draft

**Comment by BambooKim** [comment]
# bucket4j
## 개념
### 사용 알고리즘
Token Bucket 알고리즘을 사용했다.
### bandwidth
multiple bandwith를 사용할 수 있다.
bandwidth의 구성요소는 다음과 같다.
* **capacity**. 버킷에 있는 토큰 수를 지정
* **refill**. 얼마나 빨리 버킷에 토큰을 채울 지 주기를 지정
  * 예) 분당 3개, 초당 1개 등등
* **initial tokens**. 처음 버킷의 토큰 수를 지정
* **id**. 각 bandwidth의 식별자
### refill
다음의 세 가지 타입이 있다.
* **Greedy**. 바로바로
* **Interval**. 
* **IntervallyAligned**.

**Comment by BambooKim** [comment]
## TODO
### API별 처리율 제한 정책 결정
- [ ] 각 API 별 파라미터
* 초기 토큰 수 (capacity)
* refill 토큰 수 
* refill duration
