### ISSUE TITLE
[기능] 프로필 가져올 때 이미지 선택 안한 일기 갯수 가져오기?

### ISSUE THREAD

**Issue by bluejoyq** [GrimUriCapstone/backend#35]
이런 느낌으로 하나 있어야할듯 한데.

**Comment by BambooKim** [comment]
상단 메뉴바 노티 개수면, 나중에 SNS 기능 추가했을 때 알림이 필요한 기능이 생길 수도 있으니
MVP가 끝나면 다시 종합적으로 얘기해 봅시다.
구현을 어떻게 할지는 어떤 것을 포함하느냐에 따라 달라질 것 같네요

**Comment by BambooKim** [comment]
다음의 일기에 대해 카운트한다.
* 이미지 생성은 완료되었지만
* 이미지 선택은 하지 않은
