### ISSUE TITLE
[기능] 최근 생성된 이미지 목록 조회

### ISSUE THREAD

**Issue by bluejoyq** [GrimUriCapstone/backend#48]

**Comment by BambooKim** [comment]
좀 더 상세하게 설명해 주세요

* 특정 사용자의 것만인지?
* 대표 이미지 선택한 일기들의 이미지만인지?
* '최근'의 기준은?
* 범위는? (특정 기간 또는 전체?)

**Comment by BambooKim** [comment]
### 요구사항
* 조회되는 Diary의 User: Anybody
* 대표 이미지 선택한 Diary들만
* 공개 Diary들만
* 가장 최근 생성일자부터
* 범위: 프론트에서 지정(Query Param으로)

**Comment by BambooKim** [comment]
@bluejoyq 
### 요청 경로
* `GET` `/api/v1/diary/recent`
### 특이사항
* 페이지로 조회됨.
* 요청 시 Query Parameter에 `createdAt,DESC`를 추가해야 함.

자세한 사항은 스웨거 참조.
