### ISSUE TITLE
[기능] 그림의 스타일 등 프롬프트 내용 전달

### ISSUE THREAD

**Issue by BambooKim** [GrimUriCapstone/backend#53]
### 메시지 큐에 담길 메시지의 형태
> ```json
> {
>     "diaryId": "integer",
>     "originalContent": "String",
>     "userEmail": "String"
> }
> ```

내용은 다음과 같습니다.
* **`diaryId`**.  일기의 id
* **`originalContent`**. 작성한 일기의 원문
* **`userEmail`**. 일기를 작성한 사용자의 이메일

_Originally posted by @BambooKim in https://github.com/GrimUriCapstone/backend/issues/19#issuecomment-1504608024_

**Comment by evileyemovic** [comment]
{
	"diaryId": diaryId,
	"text" : text
	"userEmail": userEmail
	"themeid": themeid
	"styleid": styleid
}

**Comment by BambooKim** [comment]
@evileyemovic 

Camalcase 네이밍을 사용하는 게 좋을것 같아서 
`themeid` -> `themeId`로, `styleid` -> `styleId`로 수정해도 괜찮을까요?

**Comment by BambooKim** [comment]
@bluejoyq 다음과 같이 Request Body를 수정하시면 됩니다.

### Request Body
``` json
{
  "title": "string",
  "content": "string",
  "open": true,
  "styleId": 0,
  "themeId": 0
}
```
