### ISSUE TITLE
[기능] 이미지 액세스 API

### ISSUE THREAD

**Issue by BambooKim** [GrimUriCapstone/backend#8]
## 작업 목록
공통적으로 redirection을 이용.
### 대표 이미지 액세스
- [x] Request Path Variable에 `Long diaryId` 전달
- [x] 해당 `diaryId`가 `userSeq`의 것인지 확인
- [x] `diaryId`가 `selected`인지 아닌지 확인 (expected `true`)
- [x]  `diaryId`가 갖는 대표 이미지 URL 조회
- [x] 해당 URL을 헤더에 넣어 redirect
### 후보 이미지 액세스
- [x] Request Path Variable에 `Long diaryId`, `imageId` 전달
- [x] 해당 `diaryId`가 `userSeq`의 것인지 확인
- [x] `diaryId`가 `selected`인지 아닌지 확인 (expected `false`)
- [x] `diaryId`의 `imageId` 이미지의 URL 조회
- [x] 해당 URL을 헤더에 넣어 redirect

**Comment by BambooKim** [comment]
## Discussion
### 후보 이미지 액세스
- 후보 이미지는 두 개 이상의 복수개일 수 있음.
- 리디렉션 방식을 이용해 접근할 경우, front에서 back에 후보 이미지의 개수만큼 Request를 보내야 함 (예를 들어 5개의 후보 이미지가 있고, 5개의 후보 이미지를 보여줘야 한다면, 리디렉션 요청을 5번 보내야 함.
- 백엔드에서는, Request가 있을 때마다 DB에 쿼리를 날려 데이터를 조회함.
- DB 쿼리는 보통 비용이 큰 작업으로 간주되어, 쿼리 횟수를 최소화 하는것이 보편적으로 좋은 방식으로 여겨짐.
- 후보 이미지 액세스에 리디렉션 방식을 사용하면, 위와 같이 DB 쿼리 작업양이 상대적으로 많아짐.
- 따라서 리디렉션 방식은 대표 이미지 액세스에만 사용하고, 후보 이미지 액세스는 리디렉션 방식보다, 백엔드에서 넘겨주는 이미지 URL 목록을 이용하는 방식이 적합하다고 판단함.

@bluejoyq 검토후 회신바랍니다.

**Comment by bluejoyq** [comment]
@BambooKim 후보 이미지 버킷은 퍼블릭 액세스가 가능하게? (혹은 프론트 도메인에서만 접근 가능하게 해서) 구현하면 될 듯 합니다.
